#!/usr/bin/env python3
"""font/font8x16.txt から src/video/font_rom.veryl を生成する.

フォントソース: https://github.com/sabas0ba/font8x16-workbench (CC0 1.0)
形式: "GLYPH 0xHH name" ヘッダ + 16行x8列の '.'/'#' ビットマップ

生成するROMのデータレイアウト:
  - 各バイト: bit0 = 左端(col0), bit7 = 右端(col7)  [LSB-left]
  - 未定義コード (0x00-0x1F, 0x7F) は全行0x00

依存: Python標準ライブラリのみ
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FONT_SRC = REPO_ROOT / "font" / "font8x16.txt"
OUT_PATH = REPO_ROOT / "src" / "video" / "font_rom.veryl"

GLYPH_ROWS = 16
GLYPH_COLS = 8
CODE_MIN = 0x00
CODE_MAX = 0x7F

HEADER_RE = re.compile(r"^GLYPH\s+0x([0-9A-Fa-f]{2})\s+(\S.*)$")


def parse_font(text: str) -> dict[int, list[int]]:
    glyphs: dict[int, list[int]] = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("#"):
            continue
        m = HEADER_RE.match(line)
        if not m:
            raise ValueError(f"line {i}: unexpected line: {line!r}")
        code = int(m.group(1), 16)
        if not (CODE_MIN <= code <= CODE_MAX):
            raise ValueError(f"line {i}: code 0x{code:02x} out of range")
        if code in glyphs:
            raise ValueError(f"line {i}: duplicated glyph 0x{code:02x}")
        rows: list[int] = []
        for r in range(GLYPH_ROWS):
            if i >= len(lines):
                raise ValueError(f"glyph 0x{code:02x}: missing row {r}")
            row = lines[i].strip()
            i += 1
            if len(row) != GLYPH_COLS or any(c not in ".#" for c in row):
                raise ValueError(f"glyph 0x{code:02x} row {r}: bad row {row!r}")
            # LSB-left: 左端(col0)をbit0に割り当てる
            value = sum(1 << col for col, c in enumerate(row) if c == "#")
            rows.append(value)
        glyphs[code] = rows
    if not glyphs:
        raise ValueError("no glyphs found")
    return glyphs


def render_veryl(glyphs: dict[int, list[int]]) -> str:
    out: list[str] = []
    out.append("// AUTOGENERATED by scripts/gen_font_rom.py -- DO NOT EDIT")
    out.append("// source: font/font8x16.txt (font8x16-workbench, CC0 1.0)")
    out.append("//")
    out.append("// 8x16フォントROM (ASCII 0x00-0x7F, 未定義コードは全0)")
    out.append("// 各バイト: bit0=左端(col0) [LSB-left]")
    out.append("// 実装: グリフ単位のcase式で128bitパック定数(row0が下位)を引き，")
    out.append("// 行はシフトで選択する (Verylは通常moduleのinitialで代入不可，")
    out.append("// また数百アームの単一caseはコンパイラのstack overflowを誘発するため)")
    out.append("module FontRom (")
    out.append("    i_clk : input  clock   ,")
    out.append("    i_code: input  logic<7>, // ASCIIコード")
    out.append("    i_row : input  logic<4>, // グリフ内の行 (0-15)")
    out.append("    o_line: output logic<8>, // 1行分のピクセル (1サイクル遅れ)")
    out.append(") {")
    out.append("    var glyph  : logic<128>;")
    out.append("    var shifted: logic<128>;")
    out.append("    var q      : logic<8>  ;")
    out.append("")
    out.append("    always_comb {")
    out.append("        glyph = case i_code {")
    for code in sorted(glyphs):
        rows = glyphs[code]
        packed = sum(value << (8 * r) for r, value in enumerate(rows))
        if packed == 0:
            continue
        ch = chr(code) if 0x20 <= code <= 0x7E else "?"
        out.append(f"            {code}: 128'h{packed:032x}, // '{ch}'")
    out.append("            default: 128'h0,")
    out.append("        };")
    out.append("    }")
    out.append("")
    out.append("    always_comb {")
    out.append("        shifted = glyph >> {i_row, 3'b000};")
    out.append("    }")
    out.append("")
    out.append("    always_ff (i_clk) {")
    out.append("        q = shifted[7:0];")
    out.append("    }")
    out.append("")
    out.append("    assign o_line = q;")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    glyphs = parse_font(FONT_SRC.read_text(encoding="utf-8"))
    OUT_PATH.write_text(render_veryl(glyphs), encoding="utf-8", newline="\n")
    covered = ", ".join(f"0x{c:02x}" for c in sorted(glyphs)[:3])
    print(f"generated {OUT_PATH.relative_to(REPO_ROOT)}: "
          f"{len(glyphs)} glyphs (first: {covered} ...)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
